# Generated by Django 3.1.7 on 2021-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_ower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ower',
            new_name='owner',
        ),
    ]
